#!/bin/bash

sudo pacman -S  ttf-jetbrains-mono-nerd xorg-xrander xorg-init bspwm polybar picom sxhkd rofi

# Install yay

pacman -S --needed git base-devel
git clone https://aur.archlinux.org/yay.git
cd yay && makepkg -si
yay -S  --noconfirm  -q ttf-material-icons-git otf-material-icons-git ttf-unifont otf-unifont ttf-font-awesome-5 otf-font-awesome-5