#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d code office graphics mail web

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#AutoStart application
sxhkd &
picom --config $HOME/.config/picom/picom.conf &
nitrogen --restore &
dunst &
polybar &
